#!/bin/sh -e

export PATH=/home/alu/.cargo/bin:$PATH

if [ ! -d sp ]; then
  git clone 'https://github.com/cccb/servicepoint.git' sp
else
  ( cd sp; git pull )
fi

make -C sp/crates/servicepoint_binding_c/examples/lang_c

ln -fs sp/crates/servicepoint_binding_c/examples/lang_c/include/servicepoint.h sp.h
ln -fs sp/target/release/libservicepoint_binding_c.a libsp.a
