#!/bin/sh -e

make all pbm

pbms2sp -r -x -s -20 frame-??.pbm
sleep 1
spclr
sleep 3

robots -t -s -a -d -3
sleep 1
spclr
sleep 3

bubbles -x -s -30
sleep 1
spclr
sleep 3

mktty | tty2sp -x -s
sleep 1
spclr
sleep 3

disks -x -s -120
sleep 1
spclr
sleep 3

robots -t -s -b -d -3
sleep 1
spclr
sleep 3

tunnel -x -s -30
sleep 1
spclr
sleep 3

eyes -x -s -2
sleep 1
spclr
sleep 3

watch -x -s -t 10
sleep 1
spclr
sleep 3

cat << EOF | tty2sp -s -x
app
https://github.com/arfst23/ServicePoint

lib
https://github.com/cccb/servicepoint
EOF
sleep 5
spclr
