#!/usr/bin/perl -w
################################################################################

use strict;
use Data::Dumper;

$| = 1;

my $url = 'https://sbahn.berlin/index.php?type=9710697120&station=128&L=0';

################################################################################
# >>> schedule

sub schedule()
{
  my $schedule = `curl -s '$url' | iconv -f utf-8 -t iso-8859-15 -c`;
  $schedule =~ s/Regionalverkehr.*//s;
  my @schedule = split 'c-stations-departure-list__time">', $schedule;

  my @connections;
  my $head = shift @schedule;
  foreach my $tail (@schedule)
  {
    $head =~ s/(.*)<.*$/$1/;
    while ($head =~ />$/)
    {
      $head =~ s/(.*)<.*$/$1/;
    }
    $head =~ s/.*>//s;

    $_ = $tail;
    s/^\s+//;
    if (/^(\d\d:\d\d)\s/)
    {
      my $time = $1;
      s/.*c-stations-departure-list__destination">//s;
      s/<.*//s;
      s/^\s+//;
      s/\s+$//;
      s/^S //;
      s/^U //;
      s/^S\+U //;
      s/ \(Berlin\)$//;
      s/ Bhf$//;
      s/str\.$/straße/;
      s/.*, //;
      
      push @connections,
      {
	line => $head,
	time => $time,
	dest => $_,
      };
    }
    $head = $tail;
  }
  return @connections;
}

# <<<
################################################################################

while (1)
{
  my @connects = schedule;
  @connects = sort { $a->{time} cmp $b->{time} } @connects;

  foreach my $connect (@connects)
  {
    $connect->{time} =~ s/://;
    $connect->{dest} =~ s/ä/ae/g;
    $connect->{dest} =~ s/ö/oe/g;
    $connect->{dest} =~ s/ü/ue/g;
    $connect->{dest} =~ s/ß/ss/g;
    printf "%4s %-3s %s\n", $connect->{time}, $connect->{line}, $connect->{dest};
    
  }
  print "\n";
  sleep 30;
}

################################################################################
